/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.walison.telas;

import br.com.walison.comunicador.BandeiraCartao;
import br.com.walison.comunicador.IComunicadorFactory;
import br.com.walison.comunicador.MasterCardComunicadorFactory;
import br.com.walison.comunicador.VisaComunicadorFactory;
import br.com.walison.comunicador.emissor.IEmissor;
import br.com.walison.comunicador.receptor.IReceptor;
import br.com.walison.dados.Cliente;
import br.com.walison.dados.Funcionario;
import br.com.walison.dados.ItensVenda;
import br.com.walison.dados.Produto;
import br.com.walison.dados.Venda;
import br.com.walison.repositorio.RepositorioCliente;
import br.com.walison.repositorio.RepositorioFuncionario;
import br.com.walison.repositorio.RepositorioProduto;
import br.com.walison.repositorio.RepositorioVenda;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author walison
 */
public class TelaVenda extends javax.swing.JFrame {

    Funcionario funcionarioAtivo;
    Cliente cliente; 
    Produto produto;
    ArrayList<ItensVenda> itens = new ArrayList<>();
    
    TabelaCarrinho tabelaCarrinhoModel; 
    
   
    /**
     * Creates new form TelaVEnda
     */
    public TelaVenda() {
        initComponents();
    }

    public TelaVenda(Funcionario funcionario) {
        this();
        this.funcionarioAtivo = funcionario;
        
        this.jLabelFuncionarioAtivo.setText("Funcionário ativo: "+funcionario.getNome());
        
        this.tabelaCarrinhoModel = new TabelaCarrinho();
        this.jTable1.setModel(tabelaCarrinhoModel);
        
        jTextFieldPreco.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodProduto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabelFuncionarioAtivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdicionarProduto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");
        setResizable(false);

        jLabel1.setText("nome cliente:");

        jButtonBuscarCliente.setText("buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("cód. produto:");

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("quantidade:");

        jLabelFuncionarioAtivo.setText("funcionário ativo:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonAdicionarProduto.setText("adicionar");
        jButtonAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarProdutoActionPerformed(evt);
            }
        });

        jButton2.setText("VENDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new DefaultComboBoxModel<>(BandeiraCartao.values()));

        jLabel4.setText("cartão");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("PREÇO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFuncionarioAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodProduto)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox1, 0, 92, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldPreco)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionarProduto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncionarioAtivo)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        
        RepositorioCliente repositorioCliente = RepositorioCliente.getInstance();
        
        //buscar cliente no sistema 
        List<Cliente> listaClientes = repositorioCliente.listarTodos();
        
        if (listaClientes.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Não existem clientes cadastrados no sistema");
            
        } else {
            
            String nomeCliente = jTextFieldNomeCliente.getText();
            
            for (Cliente cliente : listaClientes) {
                
                if (cliente.getNome().equals(nomeCliente)) {
                    
                    JOptionPane.showMessageDialog(this, "usuário encontrado e adicionado");
                    
                    this.cliente = cliente;
                    break;
                    
                } else {
                    
                    System.out.println("cliente não encontrado");
                    
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       RepositorioProduto repositorioProduto = RepositorioProduto.getInstace();
       
       List<Produto> listaProdutos = repositorioProduto.listarTodos();
       
       if (listaProdutos.isEmpty()) {
           
           JOptionPane.showMessageDialog(this, "Não existem produtos cadastrados no sistema");
           
       } else {
           
           int codProduto = Integer.parseInt(jTextFieldCodProduto.getText());
           
           for (Produto produto : listaProdutos) {
               
               if (produto.getCodigo() == codProduto) {
                   
                   JOptionPane.showMessageDialog(this,"Produto encontrado");
                   
                   this.produto = produto;
                   break;
               } else {
                   
                   System.out.println("produto não encontrado");
               }
           }
           
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarProdutoActionPerformed
        
        int quantidade = Integer.parseInt(jTextFieldQuantidade.getText());
        
        ItensVenda item = new ItensVenda(quantidade, this.produto);
        this.tabelaCarrinhoModel.adicionarItem(item);
        
        //atualiza a tabela 
        this.tabelaCarrinhoModel.fireTableDataChanged();
        
        System.out.println("item inserido na tabela");
        
        this.itens.add(item);
        
        //atualiza o preço  
        jTextFieldPreco.setText(String.valueOf(this.precoTotalVenda()));
        
        //limpa campos do produto
        jTextFieldCodProduto.setText("");
        jTextFieldQuantidade.setText("");
        
    }//GEN-LAST:event_jButtonAdicionarProdutoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //forma pagamento 
        BandeiraCartao bandeiraCartao = (BandeiraCartao) jComboBox1.getSelectedItem();
        
        //validar pagamento
        System.out.println(bandeiraCartao);
        
        IComunicadorFactory comunicador = null; 
        
        if (bandeiraCartao == BandeiraCartao.MASTERCARD) {
            comunicador = new MasterCardComunicadorFactory();
            
        } else if (bandeiraCartao == BandeiraCartao.VISA) {
            comunicador = new VisaComunicadorFactory();
        }
        
        IEmissor emissor = comunicador.createEmissor();
        IReceptor receptor = comunicador.createReceptor();
        
        emissor.enviar("valor da transação = " + this.precoTotalVenda());
        String mensagem = receptor.receber();
        
        JOptionPane.showMessageDialog(this, mensagem);

        //salvar venda 
        Venda venda = new Venda(funcionarioAtivo, cliente);
        venda.setItensVenda(itens);
        
        RepositorioVenda repositorioVenda = RepositorioVenda.getInstance();
        repositorioVenda.salvar(venda);
        
        //atualizar atributos funcionario 
        RepositorioFuncionario repositorioFuncionario = RepositorioFuncionario.getInstance();
        repositorioFuncionario.atualizar(funcionarioAtivo, this.precoTotalVenda()); //todo refazer calculo do lucro
        
        JOptionPane.showMessageDialog(this,"Venda concluida");
        
        this.dispose();
        
        //todo limpar campos do form de venda
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }
    
    private double precoTotalVenda() {
        
        double preco = 0;
        
        for (ItensVenda item : itens) {
            
            preco += item.getProduto().getPrecoVenda();
            
        }
        
        return preco;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionarProduto;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JComboBox<BandeiraCartao> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFuncionarioAtivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCodProduto;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
